trigger:
- develop

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
# Development deployment
- template: templates/azure-pipelines-template.yml
  parameters:
    environment: 'dev'
    subscriptionName: 'YOURPIPELINECONNECTIONNAME'
    yourFunctionName: 'YOURFUNCTIONAPPNAME'


# Production deployment (You can reuse the pipeline for multiple deployments)
#- template: templates/azure-pipelines-template.yml
#  parameters:
#    environment: 'prod'
#    subscriptionName: 'YOURPIPELINECONNECTIONNAME'
#    yourFunctionName: 'YOURFUNCTIONAPPNAME'
